Add github test actions
YandexPraktikumDublin/PotatozationOfMars pull request #11
Opened 2021-02-04 10:43 UTC by IgorNoskov

#10

2021-02-04 10:47 UTC, Babeev approved these changes

2021-02-04 12:46 UTC, MyBraza approved these changes

2021-02-05 07:30 UTC, ivan3177 requested changes

2021-02-05 07:30 UTC, ivan3177 commented on .github/workflows/ci.yml
> +        node-version: '12'
Поскольку в package.json указана минимальная версия NodeJS как 14.9.0 то и в GitHub Actions нужно указать 14ую версию ноды для прогона(криминального в этом по сути ничего нет, но лучше не устраивать рассинхрон по версиям)

2021-02-05 13:08 UTC, ivan3177 approved these changes

2021-02-05 13:50 UTC, merged