task_19
YandexPraktikumDublin/PotatozationOfMars pull request #24
Opened 2021-02-10 12:00 UTC by MyBraza

task_19 create base rendering and controlls

2021-02-10 12:49 UTC, IgorNoskov approved these changes

2021-02-10 15:07 UTC, ivan3177 requested changes

2021-02-10 15:07 UTC, ivan3177 commented on src/game/controllers/renderCanvas.ts
> +    const canvas = (canvasRef.current as unknown) as HTMLCanvasElement
у useRef ведь можно указать через дженерик тип и тогда такие "пляски" с приведением типа референса не потребуется

2021-02-10 15:07 UTC, ivan3177 commented on src/game/controllers/renderCanvas.ts
> +const renderCanvas = () => {
У меня почему-то складывается ощущение что из этого получился хук :) И его стоит перенести тогда в хуки, а ещё если это хук то и по конвенциям наименований название должно начинаться с use
Поправьте меня если это не так

2021-02-10 15:50 UTC, ivan3177 approved these changes
Решили что поправится в следующем PR по механике игры

2021-02-11 08:07 UTC, ivan3177 approved these changes

2021-02-11 08:16 UTC, merged