task_4
YandexPraktikumDublin/PotatozationOfMars pull request #5
Opened 2021-02-03 15:55 UTC by Babeev

Add Router, add empty components

2021-02-04 14:59 UTC, MyBraza approved these changes

2021-02-04 16:29 UTC, MyBraza approved these changes

2021-02-04 16:34 UTC, IgorNoskov approved these changes

2021-02-05 07:36 UTC, ivan3177 requested changes

2021-02-05 07:36 UTC, ivan3177 commented on package.json
> +    "@types/react-router-dom": "5.1.7",
Пакеты с типами TS(@types) лучше добавлять в виде devDependencies(--save-dev в npm, --dev в yarn)
Такие зависимости нужны только при разработке поскольку TypeScript для продакшена вначале компилируется в JS и уже саму типизацию на проде тащить не нужно

2021-02-05 07:36 UTC, ivan3177 commented on src/HOCs/withHeaderAndFooter.tsx
> +      <footer />
Шапку и подвал я так понимаю реализовывать будете в отдельной задаче?

2021-02-05 07:36 UTC, ivan3177 commented on src/config.ts
> +  LIDERBOARD: '/liderboard/',
LEADERBOARD :)

2021-02-05 07:37 UTC, Babeev commented on src/HOCs/withHeaderAndFooter.tsx
> +      <footer />
Да)

2021-02-05 08:21 UTC, ivan3177 approved these changes

2021-02-05 08:22 UTC, merged